service: gettogether

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev

functions:
  helloWorld:
    handler: src/functions/helloWorld.handler
    events:
      - http:
          path: api/helloworld
          method: post
      - httpApi:
          method: POST
          path: /post/api/helloworldhttp