name: Node.js CI

on:
  push:
    branches: [ Lesson13 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test:integration
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: npm run deploy:sit
    - run: npm run seed:sit
    - run: TEST_STAGE=sit npm run test:integration
    - run: npm run test:acceptance
    - run: npm run deploy:prod
